title: Felipe Curty
subtitle: Researcher, Software Engineer, and DevSecOps
logo: /assets/profile.jpg
description: Ph.D. Student and IT Infrastructure Team Leader

theme: minima

markdown: kramdown

google_analytics: UA-126216409-1
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
disqus:
  shortname: felipecrp
